image: sunbr0/microengineci:71aa5349

stages:
    - analyze
    - build
    - run

analyze:static:
    stage: analyze
    script:
        - cppcheck --suppress='*:src/external/*' src/ --force -v

build:linux:
    stage: build
    script:
        - make release
    artifacts:
        paths:
            - build/

run:linux:
    stage: run
    script:
        - ./build/µEngine --dry-run --disable-graphics
    dependencies:
        - build:linux

